#!/bin/bash
set -e

pygsti_src="${1}/pygsti/extras/interpygate"
backport_dst="src/jaqalpaq/_backports"

die() {
    echo "$1"
    exit 1
}

[ -d "${pygsti_src}" ] || die "Unable to find pyGSTi source repository"
[ -d "${backport_dst}" ] || die "Unable to find backport destination"

pygsti_commit="$(cd "${pygsti_src}" ; git rev-parse --short HEAD )"

rm -fr "${backport_dst}/_interpygate"
mkdir "${backport_dst}/_interpygate"
cp "${1}/pygsti/extras/interpygate/"*.py "${backport_dst}/_interpygate"

find "${backport_dst}/_interpygate" -iname '*.py' -exec sed \
    -e 's/\(^[ 	]*from[ 	]\+\)\.\.\.\([a-Z]\)/\1pygsti.\2/' \
    -e 's/\(^[ 	]*from[ 	]\+\)\.\.\./\1pygsti/' \
    -e 's/\(^[ 	]*from[ 	]\+\)\.\.\([a-Z]\)/\1pygsti.extras.\2/' \
    -e 's/\(^[ 	]*from[ 	]\+\)\.\./\1pygsti.extras/' \
    -e 's/\(\(target_\(op\|factory\)\|base_interpolator\|= self\)\.num_params\)/\1()/' \
    -e '/^ *@property/{N; s/^ *@property *\n\( *def num_params(\)/\1/ }' \
    -e 's/\(_op\.to\)_\(dense\)/\1\2/' \
    -e 's/^\(import numpy as _np\)$/\1 ; import scipy.linalg as _spl/' \
    -e 's/_ot\.error_generator(\([^,]*\), \([^,]*\), "pp", "logGTi-quick")/_np.real(_spl.logm(_np.dot(\1, _spl.inv(\2))))/' \
    -i {} \;

git add "${backport_dst}/_interpygate"
git commit -m "interpygate: import pyGSTi ${pygsti_commit}"
